language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: lZVeoH0NsUVldJlN3AbpSrJjDQ1BJLE/Dwl2Mb3vczDNtppDJp0Nw920PVTxizBN1f/Yfmnii2s+YIGHQG3UcXFVkEUH8SGMB6IO0Gq0uvrtnkuTIN0EERPdcGFIlC4w4P7oSHKQMRWAIFsQ0gK1pkTE/pk98A175hNzhNPFh/o9QeMWY3CCUi1kYynVlTxZo3cLpU+FzE1lDAW41YuaJ5DejMTVXmMYzHjEi9jgENv26OhddL5g+aGF5QcDn0m7h57ATL8p2+JPPZdBZn3t5Vaz5osxl+6cW7LMO/VZ5hWOgvAeGoDPMiwZG5UxYcJRtCcD6nxN5wZUD3krEPzTieVXVpiQ63E1t1U4EID9590tHTaLBqa5uEVbvUis02ZtkZvt3a7zIKA5P4hDRYuBNnBWm+MLoqh+rneG+V3g3LiBsv8EbOQqey2qhN3fzQ5n559Wcw19N1NjhvNz9bXYNQCSto7It4JHZ78ru7K46/AR8mKXLlcBQEPLUWFuiB6ZW3rn/QptGGi0OM9uAZLMI28tbdYgp9EbRiiUSd7G6fWYVxqtCE2YHg+FMlcBuETugXK781nQn74r3k3JuWGuGY5DWBODPzQszGnnvKRLU/5AnQaQHCB7ydw+y0VgZj7RzsszuJqOojEsLLI8Ydo/dtt+xuXYSCW3W7YhPOl5X2o=
  api_key:
    secure: Q9W0C1TBC3Wqak90cjzDzO46JPRWR6IvYL5A3GSIh21mBEOKYTpkFcc5gWl++aULJdV9g/nR9znbMZn1tpcgppTFudXCUPCO02BCgYHsroPXEsquX9E67H6OLA6ipsq6zRQXvVxlC/4oOfo4PaeLoiUoyPvR9SRsJI64674trDoKNqBpQbsY19r3E2eXe2sv8jAkT3dHE5IWZf0KVUoaAlZIwXjJh+pnz+1o56pssYvU2zV1fTkSld2ot5BmGcZSRvEJdEaSc53skC4W7rzm0UobAsDVozoSHFs6JcOeG1lI6jUzl98MlAqib34iedbO9WDd+Afje6VLAcAN0iSH6Im2nwHDpSVGfnc8Ahx5pRX2XQb8Gk5FRdz6HYlYOeKasuh/qcZqF/+pCuoh5an7Txa2eVuacb3KmEyMz1nKU1lPsifRXrAF5bymgktj8cZXiFGaBqp+5m4aQQxEm3tEH+wRGDgEaDcpPBYmHh020XVvQYd35TOfqMZ7jBNCATTsR6gKdi4FqkNvbhJZsz+wu54Pt3NacEKlGXt7y2ePbzNGUURGPFJrHLKB398uhUIyksA3ILu/thFYDiDQ2Ira22tlcXwIhjWt9TbZ0BdxPFb3um/MVjJ5QKai7F5EUZ0RQH3HOw1k2kAVbCChgZg6N6Fj1bikeCGzcWWAeYdqOsM=
  on:
    tags: true
    repo: thelounge/thelounge-theme-zenburn
    branch: master
